@HttpRequestFunction_HostAddress = http://localhost:5173

GET {{HttpRequestFunction_HostAddress}}/hello
Accept: application/json

###

GET {{HttpRequestFunction_HostAddress}}/fetch
Accept: application/json

###

POST {{HttpRequestFunction_HostAddress}}/echo
Content-Type: application/json

{"message": "Hello from HTTP request!"}

###
